"""initial normalized schema

Ten tables: three reference (protocols, threat_types, mitre_techniques), five
observation (hosts, packets, flows, alerts, alert_techniques), and two derived
(protocol_stats, pipeline_runs). See netwatch/db/models.py for why each one
exists.

Autogenerated from the ORM metadata, then hand-edited in two places, both
marked below: the `severity_level` enum has to be created and dropped
explicitly (Alembic creates it implicitly on first use but never drops it, so
`downgrade` would leave the type behind and the next `upgrade` would fail),
and the composite indexes are created after the tables are populated in a
real deployment.

Revision ID: 9f1a2965aebf
Revises:
Create Date: 2026-09-02
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9f1a2965aebf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Hand-edited: create the enum up front rather than letting the first
    # column that references it do so implicitly, so its lifecycle is
    # symmetric with the DROP TYPE in downgrade().
    severity = postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO',
                               name='severity_level')
    severity.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_internal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('country', sa.String(length=32), server_default=sa.text("'UNKNOWN'"), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('packets_sent', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('packets_recv', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('bytes_sent', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('bytes_recv', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('alert_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('threat_score', sa.Double(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('threat_score >= 0 AND threat_score <= 100', name='ck_hosts_threat_score'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_index('ix_hosts_country', 'hosts', ['country'], unique=False)
    op.create_index('ix_hosts_packets_sent', 'hosts', [sa.literal_column('packets_sent DESC')], unique=False)
    op.create_index('ix_hosts_threat_score', 'hosts', [sa.literal_column('threat_score DESC')], unique=False)
    op.create_table('mitre_techniques',
    sa.Column('technique_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tactic', sa.String(length=48), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('technique_id')
    )
    op.create_index('ix_mitre_tactic', 'mitre_techniques', ['tactic'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=24), server_default=sa.text("'engine'"), nullable=False),
    sa.Column('window_s', sa.Double(), nullable=False),
    sa.Column('packets_received', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('packets_parsed', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('packets_persisted', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('packets_dropped', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('packets_failed', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('alerts_generated', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('packets_per_s', sa.Double(), server_default=sa.text('0'), nullable=False),
    sa.Column('latency_p50_ms', sa.Double(), server_default=sa.text('0'), nullable=False),
    sa.Column('latency_p95_ms', sa.Double(), server_default=sa.text('0'), nullable=False),
    sa.Column('latency_p99_ms', sa.Double(), server_default=sa.text('0'), nullable=False),
    sa.Column('peak_rss_mb', sa.Double(), server_default=sa.text('0'), nullable=False),
    sa.Column('cpu_percent', sa.Double(), server_default=sa.text('0'), nullable=False),
    sa.Column('stage_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('window_s > 0', name='ck_run_window'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_runs_source_ts', 'pipeline_runs', ['source', sa.literal_column('ts DESC')], unique=False)
    op.create_table('protocols',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('layer', sa.String(length=4), nullable=False),
    sa.Column('risk', sa.String(length=8), server_default=sa.text("'INFO'"), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('threat_types',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('detector', sa.String(length=48), nullable=False),
    sa.Column('default_severity', postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity_level', create_type=False), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_threat_types_detector', 'threat_types', ['detector'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity_level', create_type=False), nullable=False),
    sa.Column('threat_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('src_host_id', sa.BigInteger(), nullable=True),
    sa.Column('dst_host_id', sa.BigInteger(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol_id', sa.SmallInteger(), nullable=True),
    sa.Column('confidence', sa.Double(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ack_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_alerts_confidence'),
    sa.ForeignKeyConstraint(['dst_host_id'], ['hosts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.ForeignKeyConstraint(['src_host_id'], ['hosts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['threat_type_id'], ['threat_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_ack_ts', 'alerts', ['acknowledged', sa.literal_column('ts DESC')], unique=False)
    op.create_index('ix_alerts_open_critical', 'alerts', [sa.literal_column('ts DESC')], unique=False, postgresql_where=sa.text("severity = 'CRITICAL' AND acknowledged IS false"))
    op.create_index('ix_alerts_severity_ts', 'alerts', ['severity', sa.literal_column('ts DESC')], unique=False)
    op.create_index('ix_alerts_src_ts', 'alerts', ['src_host_id', sa.literal_column('ts DESC')], unique=False)
    op.create_index('ix_alerts_ts', 'alerts', [sa.literal_column('ts DESC')], unique=False)
    op.create_index('ix_alerts_ts_src_type', 'alerts', [sa.literal_column('ts DESC'), 'src_host_id', 'threat_type_id'], unique=False)
    op.create_index('ix_alerts_type_ts', 'alerts', ['threat_type_id', sa.literal_column('ts DESC')], unique=False)
    op.create_table('flows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('src_host_id', sa.BigInteger(), nullable=False),
    sa.Column('dst_host_id', sa.BigInteger(), nullable=False),
    sa.Column('src_port', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('dst_port', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('protocol_id', sa.SmallInteger(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('packets', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('flags_seen', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('state', sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.ForeignKeyConstraint(['dst_host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.ForeignKeyConstraint(['src_host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src_host_id', 'dst_host_id', 'src_port', 'dst_port', 'protocol_id', name='uq_flow_tuple')
    )
    op.create_index('ix_flows_bytes', 'flows', [sa.literal_column('bytes DESC')], unique=False)
    op.create_index('ix_flows_last_seen', 'flows', [sa.literal_column('last_seen DESC')], unique=False)
    op.create_index('ix_flows_src_dst', 'flows', ['src_host_id', 'dst_host_id', 'packets', 'bytes'], unique=False)
    op.create_index('ix_flows_src_last', 'flows', ['src_host_id', sa.literal_column('last_seen DESC')], unique=False)
    op.create_table('packets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('src_host_id', sa.BigInteger(), nullable=False),
    sa.Column('dst_host_id', sa.BigInteger(), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol_id', sa.SmallInteger(), nullable=False),
    sa.Column('frame_len', sa.Integer(), nullable=False),
    sa.Column('payload_len', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tcp_flags', sa.String(length=32), nullable=True),
    sa.Column('entropy', sa.Double(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_malicious', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('l7', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('frame_len >= 0', name='ck_packets_frame_len'),
    sa.ForeignKeyConstraint(['dst_host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.ForeignKeyConstraint(['src_host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_packets_dst_ts', 'packets', ['dst_host_id', sa.literal_column('ts DESC')], unique=False)
    op.create_index('ix_packets_proto_ts', 'packets', ['protocol_id', sa.literal_column('ts DESC')], unique=False)
    op.create_index('ix_packets_src_proto_len', 'packets', ['src_host_id', 'protocol_id', 'frame_len'], unique=False)
    op.create_index('ix_packets_src_ts', 'packets', ['src_host_id', sa.literal_column('ts DESC')], unique=False)
    op.create_index('ix_packets_ts', 'packets', [sa.literal_column('ts DESC')], unique=False)
    op.create_table('protocol_stats',
    sa.Column('bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('protocol_id', sa.SmallInteger(), nullable=False),
    sa.Column('packets', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('alerts', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('bucket', 'protocol_id')
    )
    op.create_index('ix_pstat_bucket', 'protocol_stats', [sa.literal_column('bucket DESC')], unique=False)
    op.create_table('alert_techniques',
    sa.Column('alert_id', sa.BigInteger(), nullable=False),
    sa.Column('technique_id', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['mitre_techniques.technique_id'], ),
    sa.PrimaryKeyConstraint('alert_id', 'technique_id')
    )
    op.create_index('ix_at_technique_ts', 'alert_techniques', ['technique_id', sa.literal_column('ts DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_at_technique_ts', table_name='alert_techniques')
    op.drop_table('alert_techniques')
    op.drop_index('ix_pstat_bucket', table_name='protocol_stats')
    op.drop_table('protocol_stats')
    op.drop_index('ix_packets_ts', table_name='packets')
    op.drop_index('ix_packets_src_ts', table_name='packets')
    op.drop_index('ix_packets_src_proto_len', table_name='packets')
    op.drop_index('ix_packets_proto_ts', table_name='packets')
    op.drop_index('ix_packets_dst_ts', table_name='packets')
    op.drop_table('packets')
    op.drop_index('ix_flows_src_last', table_name='flows')
    op.drop_index('ix_flows_src_dst', table_name='flows')
    op.drop_index('ix_flows_last_seen', table_name='flows')
    op.drop_index('ix_flows_bytes', table_name='flows')
    op.drop_table('flows')
    op.drop_index('ix_alerts_type_ts', table_name='alerts')
    op.drop_index('ix_alerts_ts_src_type', table_name='alerts')
    op.drop_index('ix_alerts_ts', table_name='alerts')
    op.drop_index('ix_alerts_src_ts', table_name='alerts')
    op.drop_index('ix_alerts_severity_ts', table_name='alerts')
    op.drop_index('ix_alerts_open_critical', table_name='alerts', postgresql_where=sa.text("severity = 'CRITICAL' AND acknowledged IS false"))
    op.drop_index('ix_alerts_ack_ts', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_threat_types_detector', table_name='threat_types')
    op.drop_table('threat_types')
    op.drop_table('protocols')
    op.drop_index('ix_pipeline_runs_source_ts', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index('ix_mitre_tactic', table_name='mitre_techniques')
    op.drop_table('mitre_techniques')
    op.drop_index('ix_hosts_threat_score', table_name='hosts')
    op.drop_index('ix_hosts_packets_sent', table_name='hosts')
    op.drop_index('ix_hosts_country', table_name='hosts')
    op.drop_table('hosts')
    # ### end Alembic commands ###

    # Hand-edited: Alembic drops the tables but not the type they referenced.
    # Without this, a downgrade leaves severity_level behind and the next
    # upgrade fails with "type already exists".
    postgresql.ENUM(name='severity_level').drop(op.get_bind(), checkfirst=True)
